title: "Dodona Docs"
remote_theme: dodona-edu/just-the-docs

# theme config
search_enabled: true
aux_links:
  "Ga naar Dodona":
    - "https://dodona.ugent.be"
heading_anchors: true
ga_tracking: UA-76309350-2

collections:
  news:
    output: true
    # here :name is the language
    permalink: /:name/news/:year/:month/:day/:title/
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: news
      parent: Nieuws
